export const EASY_MODULES_SUITE = [
  {
    id: "easy-loot",
    moduleIds: ["easy-loot", "auto-loot"],
    globalApis: ["easyLoot", "autoLoot"],
    title: "EasyLoot",
    descriptionKey: "EASYMODULES.Suite.EasyLoot.Description",
    actionLabelKey: "EASYMODULES.Suite.EasyLoot.Action",
    configLabelKey: "EASYMODULES.Actions.Configure",
    iconClass: "fas fa-sack-dollar",
    accessTier: "free",
    accessLabelKey: "EASYMODULES.Access.Free",
    order: 10,
    launchMethods: ["generate"],
    configureMethods: ["openConfiguration", "openConfig", "configure", "configureAndGenerate"],
    resetMethods: ["resetSettings", "restoreDefaults", "resetToDefaults", "resetConfiguration"]
  },
  {
    id: "easy-magic-items",
    moduleIds: ["easy-magic-items"],
    globalApis: ["easyMagicItems"],
    title: "EasyMagicItems",
    descriptionKey: "EASYMODULES.Suite.EasyMagicItems.Description",
    actionLabelKey: "EASYMODULES.Suite.EasyMagicItems.Action",
    iconClass: "fas fa-wand-sparkles",
    accessTier: "free",
    accessLabelKey: "EASYMODULES.Access.Free",
    order: 20,
    launchMethods: ["start", "open", "launch"],
    configureMethods: ["openConfiguration", "openConfig", "configure"],
    resetMethods: ["resetSettings", "restoreDefaults", "resetToDefaults", "resetConfiguration"]
  },
  {
    id: "easy-trials",
    moduleIds: ["easy-trials", "trials-of-fate"],
    globalApis: ["easyTrials", "trialsOfFate"],
    title: "EasyTrials",
    descriptionKey: "EASYMODULES.Suite.EasyTrials.Description",
    actionLabelKey: "EASYMODULES.Suite.EasyTrials.Action",
    iconClass: "fas fa-dice-d20",
    accessTier: "free",
    accessLabelKey: "EASYMODULES.Access.Free",
    order: 30,
    launchMethods: ["start", "open", "launch"],
    configureMethods: ["openConfiguration", "openConfig", "configure"],
    resetMethods: ["resetSettings", "restoreDefaults", "resetToDefaults", "resetConfiguration"]
  },
  {
    id: "easy-wounds",
    moduleIds: ["easy-wounds"],
    globalApis: ["easyWounds"],
    title: "EasyWounds",
    descriptionKey: "EASYMODULES.Suite.EasyWounds.Description",
    actionLabelKey: "EASYMODULES.Suite.EasyWounds.Action",
    configLabelKey: "EASYMODULES.Actions.Configure",
    iconClass: "fas fa-heart-crack",
    accessTier: "free",
    accessLabelKey: "EASYMODULES.Access.Free",
    order: 40,
    launchMethods: ["refresh"],
    configureMethods: ["openConfiguration", "openConfig", "configure"],
    resetMethods: ["resetSettings", "restoreDefaults", "resetToDefaults", "resetConfiguration"]
  },
  {
    id: "easy-shops",
    moduleIds: ["easy-shops"],
    globalApis: ["easyShops"],
    title: "EasyShops",
    descriptionKey: "EASYMODULES.Suite.EasyShops.Description",
    actionLabelKey: "EASYMODULES.Suite.EasyShops.Action",
    iconClass: "fas fa-store",
    accessTier: "free",
    accessLabelKey: "EASYMODULES.Access.Free",
    order: 50,
    launchMethods: ["open", "start", "launch"],
    configureMethods: ["openConfiguration", "openConfig", "configure"],
    resetMethods: ["resetSettings", "restoreDefaults", "resetToDefaults", "resetConfiguration"]
  },
  {
    id: "easy-traps",
    moduleIds: ["easy-traps", "deadly-traps"],
    globalApis: ["easyTraps", "deadlyTraps"],
    title: "EasyTraps",
    descriptionKey: "EASYMODULES.Suite.EasyTraps.Description",
    actionLabelKey: "EASYMODULES.Suite.EasyTraps.Action",
    configLabelKey: "EASYMODULES.Actions.Configure",
    iconClass: "fas fa-dungeon",
    accessTier: "free",
    accessLabelKey: "EASYMODULES.Access.Free",
    order: 60,
    launchMethods: ["createTrap", "openLibrary", "openManager"],
    configureMethods: ["openSettings", "openConfiguration", "openConfig", "configure"],
    resetMethods: ["resetSettings", "restoreDefaults", "resetToDefaults", "resetConfiguration"]
  },
  {
    id: "easy-rest",
    moduleIds: ["easy-rest"],
    globalApis: ["easyRest"],
    title: "EasyRest",
    descriptionKey: "EASYMODULES.Suite.EasyRest.Description",
    actionLabelKey: "EASYMODULES.Status.ComingSoon",
    iconClass: "fas fa-campground",
    status: "coming-soon",
    order: 70,
    launchMethods: ["open", "start", "launch"],
    configureMethods: ["openConfiguration", "openConfig", "configure"],
    resetMethods: ["resetSettings", "restoreDefaults", "resetToDefaults", "resetConfiguration"]
  }
];
